version: '3'
services:
  postgres:
    image: postgres
    networks:
      - connection
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadinzar29

  spring-app:
    networks:
      - connection
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sadinzar29

networks:
  connection: